name: hcdesk.com
favicon: null
layout_spectrum: 0.1569158521015197
typography_spectrum: 0.12232686276547611
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.3727636900730431
  lightness: 0.8416123809292912
  saturation: 0.1237021409906447
  rhythmicContrast: 0.3215668718330562
purpose: []
